---
name: "raw"
source: "ActionView::Helpers::OutputSafetyHelper#raw"
gem: "actionview"
output: "html"
visibility: "public"
supported: false
supports_block: false
signature: "raw(stringish)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html#method-i-raw"

description: |-
  Marks a string as trusted safe, bypassing HTML escaping. Use with caution.

tag: null

arguments:
  - name: "stringish"
    position: 1
    type: "string"
    optional: false
    description: |-
      String to mark as safe.

options: []
block_arguments: []
special_behaviors: []
