---
name: "safe_concat"
source: "ActionView::Helpers::TextHelper#safe_concat"
gem: "actionview"
output: "void"
visibility: "internal"
supported: false
supports_block: false
signature: "safe_concat(string)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-safe_concat"

description: |-
  Concatenates a string to the output buffer without HTML escaping. The string must already be `html_safe`.

tag: null
arguments: []
options: []
block_arguments: []
special_behaviors: []
