// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 01:41:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *hbarray) Ref() *C.hb_array_T {
	if x == nil {
		return nil
	}
	return (*C.hb_array_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *hbarray) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewhbarrayRef converts the C object reference into a raw struct reference without wrapping.
func NewhbarrayRef(ref unsafe.Pointer) *hbarray {
	return (*hbarray)(ref)
}

// Newhbarray allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newhbarray() *hbarray {
	return (*hbarray)(allocHbarrayMemory(1))
}

// allocHbarrayMemory allocates memory for type C.hb_array_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHbarrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHbarrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHbarrayValue = unsafe.Sizeof([1]C.hb_array_T{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *hbarray) PassRef() *C.hb_array_T {
	if x == nil {
		x = (*hbarray)(allocHbarrayMemory(1))
	}
	return (*C.hb_array_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *hbbuffer) Ref() *C.hb_buffer_T {
	if x == nil {
		return nil
	}
	return (*C.hb_buffer_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *hbbuffer) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewhbbufferRef converts the C object reference into a raw struct reference without wrapping.
func NewhbbufferRef(ref unsafe.Pointer) *hbbuffer {
	return (*hbbuffer)(ref)
}

// Newhbbuffer allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newhbbuffer() *hbbuffer {
	return (*hbbuffer)(allocHbbufferMemory(1))
}

// allocHbbufferMemory allocates memory for type C.hb_buffer_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHbbufferMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHbbufferValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHbbufferValue = unsafe.Sizeof([1]C.hb_buffer_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *hbbuffer) PassRef() *C.hb_buffer_T {
	if x == nil {
		x = (*hbbuffer)(allocHbbufferMemory(1))
	}
	return (*C.hb_buffer_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *ASTDOCUMENTNODE) Ref() *C.AST_DOCUMENT_NODE_T {
	if x == nil {
		return nil
	}
	return (*C.AST_DOCUMENT_NODE_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *ASTDOCUMENTNODE) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewASTDOCUMENTNODERef converts the C object reference into a raw struct reference without wrapping.
func NewASTDOCUMENTNODERef(ref unsafe.Pointer) *ASTDOCUMENTNODE {
	return (*ASTDOCUMENTNODE)(ref)
}

// NewASTDOCUMENTNODE allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewASTDOCUMENTNODE() *ASTDOCUMENTNODE {
	return (*ASTDOCUMENTNODE)(allocASTDOCUMENTNODEMemory(1))
}

// allocASTDOCUMENTNODEMemory allocates memory for type C.AST_DOCUMENT_NODE_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocASTDOCUMENTNODEMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfASTDOCUMENTNODEValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfASTDOCUMENTNODEValue = unsafe.Sizeof([1]C.AST_DOCUMENT_NODE_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *ASTDOCUMENTNODE) PassRef() *C.AST_DOCUMENT_NODE_T {
	if x == nil {
		x = (*ASTDOCUMENTNODE)(allocASTDOCUMENTNODEMemory(1))
	}
	return (*C.AST_DOCUMENT_NODE_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *parseroptions) Ref() *C.parser_options_T {
	if x == nil {
		return nil
	}
	return (*C.parser_options_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *parseroptions) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewparseroptionsRef converts the C object reference into a raw struct reference without wrapping.
func NewparseroptionsRef(ref unsafe.Pointer) *parseroptions {
	return (*parseroptions)(ref)
}

// Newparseroptions allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newparseroptions() *parseroptions {
	return (*parseroptions)(allocParseroptionsMemory(1))
}

// allocParseroptionsMemory allocates memory for type C.parser_options_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocParseroptionsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfParseroptionsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfParseroptionsValue = unsafe.Sizeof([1]C.parser_options_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *parseroptions) PassRef() *C.parser_options_T {
	if x == nil {
		x = (*parseroptions)(allocParseroptionsMemory(1))
	}
	return (*C.parser_options_T)(unsafe.Pointer(x))
}

// safeString ensures that the string is NULL-terminated, a NULL-terminated copy is created otherwise.
func safeString(str string) string {
	if len(str) > 0 && str[len(str)-1] != '\x00' {
		str = str + "\x00"
	} else if len(str) == 0 {
		str = "\x00"
	}
	return str
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	str = safeString(str)
	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// copyPHbarrayBytes copies the data from Go slice as *C.hb_array_T.
func copyPHbarrayBytes(slice *sliceHeader) (*C.hb_array_T, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfHbarrayValue) * slice.Len,
		Cap:  int(sizeOfHbarrayValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.hb_array_T)(mem0), allocs
}
