// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 02:26:35 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *hbarray) Ref() *C.hb_array_T {
	if x == nil {
		return nil
	}
	return (*C.hb_array_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *hbarray) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewhbarrayRef converts the C object reference into a raw struct reference without wrapping.
func NewhbarrayRef(ref unsafe.Pointer) *hbarray {
	return (*hbarray)(ref)
}

// Newhbarray allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newhbarray() *hbarray {
	return (*hbarray)(allocHbarrayMemory(1))
}

// allocHbarrayMemory allocates memory for type C.hb_array_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHbarrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHbarrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHbarrayValue = unsafe.Sizeof([1]C.hb_array_T{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *hbarray) PassRef() *C.hb_array_T {
	if x == nil {
		x = (*hbarray)(allocHbarrayMemory(1))
	}
	return (*C.hb_array_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *hbbuffer) Ref() *C.hb_buffer_T {
	if x == nil {
		return nil
	}
	return (*C.hb_buffer_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *hbbuffer) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewhbbufferRef converts the C object reference into a raw struct reference without wrapping.
func NewhbbufferRef(ref unsafe.Pointer) *hbbuffer {
	return (*hbbuffer)(ref)
}

// Newhbbuffer allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newhbbuffer() *hbbuffer {
	return (*hbbuffer)(allocHbbufferMemory(1))
}

// allocHbbufferMemory allocates memory for type C.hb_buffer_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHbbufferMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHbbufferValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHbbufferValue = unsafe.Sizeof([1]C.hb_buffer_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *hbbuffer) PassRef() *C.hb_buffer_T {
	if x == nil {
		x = (*hbbuffer)(allocHbbufferMemory(1))
	}
	return (*C.hb_buffer_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *ASTDOCUMENTNODE) Ref() *C.AST_DOCUMENT_NODE_T {
	if x == nil {
		return nil
	}
	return (*C.AST_DOCUMENT_NODE_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *ASTDOCUMENTNODE) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewASTDOCUMENTNODERef converts the C object reference into a raw struct reference without wrapping.
func NewASTDOCUMENTNODERef(ref unsafe.Pointer) *ASTDOCUMENTNODE {
	return (*ASTDOCUMENTNODE)(ref)
}

// NewASTDOCUMENTNODE allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewASTDOCUMENTNODE() *ASTDOCUMENTNODE {
	return (*ASTDOCUMENTNODE)(allocASTDOCUMENTNODEMemory(1))
}

// allocASTDOCUMENTNODEMemory allocates memory for type C.AST_DOCUMENT_NODE_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocASTDOCUMENTNODEMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfASTDOCUMENTNODEValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfASTDOCUMENTNODEValue = unsafe.Sizeof([1]C.AST_DOCUMENT_NODE_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *ASTDOCUMENTNODE) PassRef() *C.AST_DOCUMENT_NODE_T {
	if x == nil {
		x = (*ASTDOCUMENTNODE)(allocASTDOCUMENTNODEMemory(1))
	}
	return (*C.AST_DOCUMENT_NODE_T)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *parseroptions) Ref() *C.parser_options_T {
	if x == nil {
		return nil
	}
	return (*C.parser_options_T)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *parseroptions) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewparseroptionsRef converts the C object reference into a raw struct reference without wrapping.
func NewparseroptionsRef(ref unsafe.Pointer) *parseroptions {
	return (*parseroptions)(ref)
}

// Newparseroptions allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func Newparseroptions() *parseroptions {
	return (*parseroptions)(allocParseroptionsMemory(1))
}

// allocParseroptionsMemory allocates memory for type C.parser_options_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocParseroptionsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfParseroptionsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfParseroptionsValue = unsafe.Sizeof([1]C.parser_options_T{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *parseroptions) PassRef() *C.parser_options_T {
	if x == nil {
		x = (*parseroptions)(allocParseroptionsMemory(1))
	}
	return (*C.parser_options_T)(unsafe.Pointer(x))
}

// allocPositionMemory allocates memory for type C.position_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPositionMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPositionValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPositionValue = unsafe.Sizeof([1]C.position_T{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *position) Ref() *C.position_T {
	if x == nil {
		return nil
	}
	return x.refde50b33c
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *position) Free() {
	if x != nil && x.allocsde50b33c != nil {
		x.allocsde50b33c.(*cgoAllocMap).Free()
		x.refde50b33c = nil
	}
}

// NewpositionRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewpositionRef(ref unsafe.Pointer) *position {
	if ref == nil {
		return nil
	}
	obj := new(position)
	obj.refde50b33c = (*C.position_T)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *position) PassRef() (*C.position_T, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refde50b33c != nil {
		return x.refde50b33c, nil
	}
	memde50b33c := allocPositionMemory(1)
	refde50b33c := (*C.position_T)(memde50b33c)
	allocsde50b33c := new(cgoAllocMap)
	allocsde50b33c.Add(memde50b33c)

	var cline_allocs *cgoAllocMap
	refde50b33c.line, cline_allocs = (C.uint)(x.line), cgoAllocsUnknown
	allocsde50b33c.Borrow(cline_allocs)

	var ccolumn_allocs *cgoAllocMap
	refde50b33c.column, ccolumn_allocs = (C.uint)(x.column), cgoAllocsUnknown
	allocsde50b33c.Borrow(ccolumn_allocs)

	x.refde50b33c = refde50b33c
	x.allocsde50b33c = allocsde50b33c
	return refde50b33c, allocsde50b33c

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x position) PassValue() (C.position_T, *cgoAllocMap) {
	if x.refde50b33c != nil {
		return *x.refde50b33c, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *position) Deref() {
	if x.refde50b33c == nil {
		return
	}
	x.line = (uint32)(x.refde50b33c.line)
	x.column = (uint32)(x.refde50b33c.column)
}

// alloc_rangeMemory allocates memory for type C.range_T in C.
// The caller is responsible for freeing the this memory via C.free.
func alloc_rangeMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOf_rangeValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOf_rangeValue = unsafe.Sizeof([1]C.range_T{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *_range) Ref() *C.range_T {
	if x == nil {
		return nil
	}
	return x.refbaf919a8
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *_range) Free() {
	if x != nil && x.allocsbaf919a8 != nil {
		x.allocsbaf919a8.(*cgoAllocMap).Free()
		x.refbaf919a8 = nil
	}
}

// New_rangeRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func New_rangeRef(ref unsafe.Pointer) *_range {
	if ref == nil {
		return nil
	}
	obj := new(_range)
	obj.refbaf919a8 = (*C.range_T)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *_range) PassRef() (*C.range_T, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refbaf919a8 != nil {
		return x.refbaf919a8, nil
	}
	membaf919a8 := alloc_rangeMemory(1)
	refbaf919a8 := (*C.range_T)(membaf919a8)
	allocsbaf919a8 := new(cgoAllocMap)
	allocsbaf919a8.Add(membaf919a8)

	var cfrom_allocs *cgoAllocMap
	refbaf919a8.from, cfrom_allocs = (C.uint)(x.from), cgoAllocsUnknown
	allocsbaf919a8.Borrow(cfrom_allocs)

	var cto_allocs *cgoAllocMap
	refbaf919a8.to, cto_allocs = (C.uint)(x.to), cgoAllocsUnknown
	allocsbaf919a8.Borrow(cto_allocs)

	x.refbaf919a8 = refbaf919a8
	x.allocsbaf919a8 = allocsbaf919a8
	return refbaf919a8, allocsbaf919a8

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x _range) PassValue() (C.range_T, *cgoAllocMap) {
	if x.refbaf919a8 != nil {
		return *x.refbaf919a8, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *_range) Deref() {
	if x.refbaf919a8 == nil {
		return
	}
	x.from = (uint32)(x.refbaf919a8.from)
	x.to = (uint32)(x.refbaf919a8.to)
}

// allocLocationMemory allocates memory for type C.location_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocLocationMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfLocationValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfLocationValue = unsafe.Sizeof([1]C.location_T{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *location) Ref() *C.location_T {
	if x == nil {
		return nil
	}
	return x.refac96ad16
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *location) Free() {
	if x != nil && x.allocsac96ad16 != nil {
		x.allocsac96ad16.(*cgoAllocMap).Free()
		x.refac96ad16 = nil
	}
}

// NewlocationRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewlocationRef(ref unsafe.Pointer) *location {
	if ref == nil {
		return nil
	}
	obj := new(location)
	obj.refac96ad16 = (*C.location_T)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *location) PassRef() (*C.location_T, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refac96ad16 != nil {
		return x.refac96ad16, nil
	}
	memac96ad16 := allocLocationMemory(1)
	refac96ad16 := (*C.location_T)(memac96ad16)
	allocsac96ad16 := new(cgoAllocMap)
	allocsac96ad16.Add(memac96ad16)

	var cstart_allocs *cgoAllocMap
	refac96ad16.start, cstart_allocs = x.start.PassValue()
	allocsac96ad16.Borrow(cstart_allocs)

	var cend_allocs *cgoAllocMap
	refac96ad16.end, cend_allocs = x.end.PassValue()
	allocsac96ad16.Borrow(cend_allocs)

	x.refac96ad16 = refac96ad16
	x.allocsac96ad16 = allocsac96ad16
	return refac96ad16, allocsac96ad16

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x location) PassValue() (C.location_T, *cgoAllocMap) {
	if x.refac96ad16 != nil {
		return *x.refac96ad16, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *location) Deref() {
	if x.refac96ad16 == nil {
		return
	}
	x.start = *NewpositionRef(unsafe.Pointer(&x.refac96ad16.start))
	x.end = *NewpositionRef(unsafe.Pointer(&x.refac96ad16.end))
}

// allocTokenMemory allocates memory for type C.token_T in C.
// The caller is responsible for freeing the this memory via C.free.
func allocTokenMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfTokenValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfTokenValue = unsafe.Sizeof([1]C.token_T{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *token) Ref() *C.token_T {
	if x == nil {
		return nil
	}
	return x.ref8d9fe5f8
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *token) Free() {
	if x != nil && x.allocs8d9fe5f8 != nil {
		x.allocs8d9fe5f8.(*cgoAllocMap).Free()
		x.ref8d9fe5f8 = nil
	}
}

// NewtokenRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewtokenRef(ref unsafe.Pointer) *token {
	if ref == nil {
		return nil
	}
	obj := new(token)
	obj.ref8d9fe5f8 = (*C.token_T)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *token) PassRef() (*C.token_T, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref8d9fe5f8 != nil {
		return x.ref8d9fe5f8, nil
	}
	mem8d9fe5f8 := allocTokenMemory(1)
	ref8d9fe5f8 := (*C.token_T)(mem8d9fe5f8)
	allocs8d9fe5f8 := new(cgoAllocMap)
	allocs8d9fe5f8.Add(mem8d9fe5f8)

	var cvalue_allocs *cgoAllocMap
	ref8d9fe5f8.value, cvalue_allocs = *(**C.char)(unsafe.Pointer(&x.value)), cgoAllocsUnknown
	allocs8d9fe5f8.Borrow(cvalue_allocs)

	var c_range_allocs *cgoAllocMap
	ref8d9fe5f8._range, c_range_allocs = x._range.PassValue()
	allocs8d9fe5f8.Borrow(c_range_allocs)

	var clocation_allocs *cgoAllocMap
	ref8d9fe5f8.location, clocation_allocs = x.location.PassValue()
	allocs8d9fe5f8.Borrow(clocation_allocs)

	var c_type_allocs *cgoAllocMap
	ref8d9fe5f8._type, c_type_allocs = (C.token_type_T)(x.kind), cgoAllocsUnknown
	allocs8d9fe5f8.Borrow(c_type_allocs)

	x.ref8d9fe5f8 = ref8d9fe5f8
	x.allocs8d9fe5f8 = allocs8d9fe5f8
	return ref8d9fe5f8, allocs8d9fe5f8

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x token) PassValue() (C.token_T, *cgoAllocMap) {
	if x.ref8d9fe5f8 != nil {
		return *x.ref8d9fe5f8, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *token) Deref() {
	if x.ref8d9fe5f8 == nil {
		return
	}
	x.value = (*byte)(unsafe.Pointer(x.ref8d9fe5f8.value))
	x._range = *New_rangeRef(unsafe.Pointer(&x.ref8d9fe5f8._range))
	x.location = *NewlocationRef(unsafe.Pointer(&x.ref8d9fe5f8.location))
	x.kind = (tokentype)(x.ref8d9fe5f8._type)
}

// safeString ensures that the string is NULL-terminated, a NULL-terminated copy is created otherwise.
func safeString(str string) string {
	if len(str) > 0 && str[len(str)-1] != '\x00' {
		str = str + "\x00"
	} else if len(str) == 0 {
		str = "\x00"
	}
	return str
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	str = safeString(str)
	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// copyPHbarrayBytes copies the data from Go slice as *C.hb_array_T.
func copyPHbarrayBytes(slice *sliceHeader) (*C.hb_array_T, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfHbarrayValue) * slice.Len,
		Cap:  int(sizeOfHbarrayValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.hb_array_T)(mem0), allocs
}
