// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 02:26:35 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "herb_go.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

