// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 01:41:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// herbextractlanguage as declared in herb/herb_go.h:20
type herbextractlanguage int32

// herbextractlanguage enumeration from herb/herb_go.h:20
const ()
