// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 02:26:35 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// tokentype as declared in herb/herb_go.h:43
type tokentype int32

// tokentype enumeration from herb/herb_go.h:43
const ()

// herbextractlanguage as declared in herb/herb_go.h:56
type herbextractlanguage int32

// herbextractlanguage enumeration from herb/herb_go.h:56
const ()
