// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 02:26:35 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go bindings for Herb - HTML-aware ERB parser
*/
package herb
