// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 01:41:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Lextobuffer function as declared in herb/herb_go.h:23
func Lextobuffer(source string, output *hbbuffer) {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	coutput, coutputAllocMap := (*C.hb_buffer_T)(unsafe.Pointer(output)), cgoAllocsUnknown
	C.herb_lex_to_buffer(csource, coutput)
	runtime.KeepAlive(coutputAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
}

// Lex function as declared in herb/herb_go.h:24
func Lex(source string) *hbarray {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	__ret := C.herb_lex(csource)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
	__v := *(**hbarray)(unsafe.Pointer(&__ret))
	return __v
}

// Lexfile function as declared in herb/herb_go.h:25
func Lexfile(path string) *hbarray {
	path = safeString(path)
	cpath, cpathAllocMap := unpackPCharString(path)
	__ret := C.herb_lex_file(cpath)
	runtime.KeepAlive(path)
	runtime.KeepAlive(cpathAllocMap)
	__v := *(**hbarray)(unsafe.Pointer(&__ret))
	return __v
}

// Parse function as declared in herb/herb_go.h:26
func Parse(source string, options *parseroptions) *ASTDOCUMENTNODE {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	coptions, coptionsAllocMap := (*C.parser_options_T)(unsafe.Pointer(options)), cgoAllocsUnknown
	__ret := C.herb_parse(csource, coptions)
	runtime.KeepAlive(coptionsAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
	__v := *(**ASTDOCUMENTNODE)(unsafe.Pointer(&__ret))
	return __v
}

// Version function as declared in herb/herb_go.h:27
func Version() *byte {
	__ret := C.herb_version()
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Prismversion function as declared in herb/herb_go.h:28
func Prismversion() *byte {
	__ret := C.herb_prism_version()
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Freetokens function as declared in herb/herb_go.h:29
func Freetokens(tokens []*hbarray) {
	ctokens, ctokensAllocMap := (**C.hb_array_T)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&tokens)).Data)), cgoAllocsUnknown
	C.herb_free_tokens(ctokens)
	runtime.KeepAlive(ctokensAllocMap)
}

// Extractrubytobuffer function as declared in herb/herb_go.h:32
func Extractrubytobuffer(source string, output *hbbuffer) {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	coutput, coutputAllocMap := (*C.hb_buffer_T)(unsafe.Pointer(output)), cgoAllocsUnknown
	C.herb_extract_ruby_to_buffer(csource, coutput)
	runtime.KeepAlive(coutputAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
}

// Extracthtmltobuffer function as declared in herb/herb_go.h:33
func Extracthtmltobuffer(source string, output *hbbuffer) {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	coutput, coutputAllocMap := (*C.hb_buffer_T)(unsafe.Pointer(output)), cgoAllocsUnknown
	C.herb_extract_html_to_buffer(csource, coutput)
	runtime.KeepAlive(coutputAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
}

// Extractrubywithsemicolons function as declared in herb/herb_go.h:34
func Extractrubywithsemicolons(source string) *byte {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	__ret := C.herb_extract_ruby_with_semicolons(csource)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Extractrubytobufferwithsemicolons function as declared in herb/herb_go.h:35
func Extractrubytobufferwithsemicolons(source string, output *hbbuffer) {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	coutput, coutputAllocMap := (*C.hb_buffer_T)(unsafe.Pointer(output)), cgoAllocsUnknown
	C.herb_extract_ruby_to_buffer_with_semicolons(csource, coutput)
	runtime.KeepAlive(coutputAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
}

// Extract function as declared in herb/herb_go.h:36
func Extract(source string, language herbextractlanguage) *byte {
	source = safeString(source)
	csource, csourceAllocMap := unpackPCharString(source)
	clanguage, clanguageAllocMap := (C.herb_extract_language_T)(language), cgoAllocsUnknown
	__ret := C.herb_extract(csource, clanguage)
	runtime.KeepAlive(clanguageAllocMap)
	runtime.KeepAlive(source)
	runtime.KeepAlive(csourceAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Extractfromfile function as declared in herb/herb_go.h:37
func Extractfromfile(path string, language herbextractlanguage) *byte {
	path = safeString(path)
	cpath, cpathAllocMap := unpackPCharString(path)
	clanguage, clanguageAllocMap := (C.herb_extract_language_T)(language), cgoAllocsUnknown
	__ret := C.herb_extract_from_file(cpath, clanguage)
	runtime.KeepAlive(clanguageAllocMap)
	runtime.KeepAlive(path)
	runtime.KeepAlive(cpathAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}
