// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 02:26:35 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package herb

/*
#cgo CFLAGS: -I.. -I../src/include -I../src
#cgo LDFLAGS: ${SRCDIR}/../../build/libherb.a ${SRCDIR}/../../vendor/prism/build/libprism.a
#include "herb_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// hbarray as declared in herb/herb_go.h:11
type hbarray C.hb_array_T

// hbbuffer as declared in herb/herb_go.h:12
type hbbuffer C.hb_buffer_T

// ASTDOCUMENTNODE as declared in herb/herb_go.h:13
type ASTDOCUMENTNODE C.AST_DOCUMENT_NODE_T

// parseroptions as declared in herb/herb_go.h:14
type parseroptions C.parser_options_T

// position as declared in herb/herb_go.h:20
type position struct {
	line           uint32
	column         uint32
	refde50b33c    *C.position_T
	allocsde50b33c interface{}
}

// _range as declared in herb/herb_go.h:25
type _range struct {
	from           uint32
	to             uint32
	refbaf919a8    *C.range_T
	allocsbaf919a8 interface{}
}

// location as declared in herb/herb_go.h:30
type location struct {
	start          position
	end            position
	refac96ad16    *C.location_T
	allocsac96ad16 interface{}
}

// token as declared in herb/herb_go.h:50
type token struct {
	value          *byte
	_range         _range
	location       location
	kind           tokentype
	ref8d9fe5f8    *C.token_T
	allocs8d9fe5f8 interface{}
}

// _predefinedsize type as declared in go/<builtin>:23
type _predefinedsize uint64

// _predefinedwchar type as declared in go/<builtin>:27
type _predefinedwchar int32

// _predefinedptrdiff type as declared in go/<builtin>:31
type _predefinedptrdiff int64
