AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - ext/erbx/test/fork_helper.rb

Metrics/AbcSize:
  Exclude:
    - ext/erbx/test/fork_helper.rb

Metrics/ClassLength:
  Exclude:
    - ext/erbx/test/**/*_test.rb

Metrics/BlockLength:
  Exclude:
    - ext/erbx/test/**/*_test.rb

Layout/LineLength:
  Max: 120
  Exclude:
    - ext/erbx/test/**/*_test.rb

Security/MarshalLoad:
  Exclude:
    - ext/erbx/test/fork_helper.rb
