AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/erbx/extconf.rb

Style/AccessorGrouping:
  Exclude:
    - lib/erbx/errors.rb
    - lib/erbx/ast/nodes.rb

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - lib/erbx/project.rb
    - lib/erbx/ast/nodes.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/erbx/ast/nodes.rb
    - lib/erbx/cli.rb
    - lib/erbx/project.rb
    - templates/template.rb
    - test/fork_helper.rb

Metrics/AbcSize:
  Exclude:
    - lib/erbx/ast/node.rb
    - lib/erbx/ast/nodes.rb
    - lib/erbx/cli.rb
    - lib/erbx/errors.rb
    - lib/erbx/project.rb
    - templates/template.rb
    - test/fork_helper.rb
    - test/snapshot_utils.rb

Metrics/ClassLength:
  Exclude:
    - lib/erbx/cli.rb
    - lib/erbx/project.rb
    - test/**/*_test.rb

Metrics/BlockLength:
  Max: 30
  Exclude:
    - Rakefile
    - "*.gemspec"
    - lib/erbx/project.rb
    - test/**/*_test.rb

Metrics/ParameterLists:
  Exclude:
    - lib/erbx/ast/nodes.rb
    - lib/erbx/errors.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/erbx/project.rb
    - lib/erbx/ast/nodes.rb

Layout/LineLength:
  Max: 120
  Exclude:
    - test/**/*_test.rb
    - lib/erbx/token.rb
    - lib/erbx/ast/nodes.rb

Layout/EmptyLines:
  Exclude:
    - lib/erbx/ast/nodes.rb
    - lib/erbx/errors.rb

Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - lib/erbx/ast/nodes.rb
    - lib/erbx/errors.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Security/Eval:
  Exclude:
    - Rakefile

Security/MarshalLoad:
  Exclude:
    - test/fork_helper.rb
