AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MixinUsage:
  Exclude:
    - bin/compare
    - bin/compare-render
    - bin/compare-compile

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/BlockDelimiters:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/herb/extconf.rb

Style/AccessorGrouping:
  Exclude:
    - lib/herb/errors.rb
    - lib/herb/ast/nodes.rb

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - lib/herb/ast/node.rb
    - lib/herb/ast/nodes.rb
    - lib/herb/engine/validators/security_validator.rb
    - lib/herb/errors.rb
    - lib/herb/parser_options.rb
    - lib/herb/prism_inspect.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/cli.rb
    - lib/herb/project.rb
    - lib/herb/prism_inspect.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb
    - templates/template.rb
    - test/**/*.rb
    - bin/**/*

Layout/LineLength:
  Enabled: false

Layout/EmptyLines:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/errors.rb

Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/errors.rb

Layout/EmptyLinesAroundClassBody:
  Exclude:
    - lib/herb/visitor.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Security/Eval:
  Exclude:
    - Rakefile
    - lib/herb/cli.rb
    - test/**/*.rb
    - bin/erubi-render
    - bin/compare-render
    - bin/compare-render

Security/MarshalLoad:
  Exclude:
    - test/fork_helper.rb

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - test/engine/secure_compiler_test.rb

Lint/UnusedMethodArgument:
  Exclude:
    - lib/herb/errors.rb

Style/IfUnlessModifier:
  Enabled: false
