AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/herb/extconf.rb

Style/AccessorGrouping:
  Exclude:
    - lib/herb/errors.rb
    - lib/herb/ast/nodes.rb

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - lib/herb/project.rb
    - lib/herb/ast/nodes.rb
    - lib/herb/cli.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/cli.rb
    - lib/herb/project.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb
    - templates/template.rb
    - test/fork_helper.rb
    - test/snapshot_utils.rb
    - bin/**/*

Metrics/AbcSize:
  Exclude:
    - lib/herb/ast/node.rb
    - lib/herb/ast/nodes.rb
    - lib/herb/cli.rb
    - lib/herb/errors.rb
    - lib/herb/project.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb
    - templates/template.rb
    - test/fork_helper.rb
    - test/snapshot_utils.rb
    - bin/**/*

Metrics/ClassLength:
  Exclude:
    - lib/herb/cli.rb
    - lib/herb/project.rb
    - lib/herb/visitor.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb
    - bin/**/*
    - test/**/*_test.rb

Metrics/ModuleLength:
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Max: 30
  Exclude:
    - Rakefile
    - "*.gemspec"
    - "**/*.rake"
    - lib/herb/cli.rb
    - lib/herb/project.rb
    - test/**/*_test.rb
    - bin/**/*

Metrics/ParameterLists:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/errors.rb
    - lib/herb/engine/validators/security_validator.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/cli.rb
    - lib/herb/project.rb
    - lib/herb/engine.rb
    - lib/herb/engine/**/*.rb
    - test/**/*.rb
    - bin/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - test/**/*_test.rb
    - lib/herb/token.rb
    - lib/herb/ast/nodes.rb
    - lib/herb/engine/error_formatter.rb
    - lib/herb/engine/debug_visitor.rb
    - lib/herb/engine/parser_error_overlay.rb
    - lib/herb/engine/validation_error_overlay.rb

Layout/EmptyLines:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/errors.rb

Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - lib/herb/ast/nodes.rb
    - lib/herb/errors.rb

Layout/EmptyLinesAroundClassBody:
  Exclude:
    - lib/herb/visitor.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Security/Eval:
  Exclude:
    - Rakefile
    - lib/herb/cli.rb
    - test/**/*.rb
    - bin/erubi-render

Security/MarshalLoad:
  Exclude:
    - test/fork_helper.rb

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - test/engine/secure_compiler_test.rb
