errors:
  fields:
    - name: message
      type: string

    - name: start
      type: position

    - name: end
      type: position

  types:
    - name: UnexpectedError
      message:
        template: "%s. Expected: `%s`, found: `%s`."
        arguments:
          - description
          - expected
          - found

      fields:
        - name: description
          type: string

        - name: expected
          type: string

        - name: found
          type: string

    - name: UnexpectedTokenError
      message:
        template: "Found `%s` when expecting `%s` at (%zu:%zu)."
        arguments:
          - token_type_to_string(found->type)
          - token_type_to_string(expected_type)
          - found->location->start->line
          - found->location->start->column

      fields:
        - name: expected_type
          type: token_type

        - name: found
          type: token

    - name: MissingOpeningTagError
      message:
        template: "Found closing tag `</%s>` at (%zu:%zu) without a matching opening tag."
        arguments:
          - closing_tag->value
          - closing_tag->location->start->line
          - closing_tag->location->start->column

      fields:
        - name: closing_tag
          type: token

    - name: MissingClosingTagError
      message:
        template: "Opening tag `<%s>` at (%zu:%zu) doesn't have a matching closing tag `</%s>`."
        arguments:
          - opening_tag->value
          - opening_tag->location->start->line
          - opening_tag->location->start->column
          - opening_tag->value

      fields:
        - name: opening_tag
          type: token

    - name: TagNamesMismatchError
      message:
        template: "Opening tag `<%s>` at (%zu:%zu) closed with `</%s>` at (%zu:%zu)."
        arguments:
          - opening_tag->value
          - opening_tag->location->start->line
          - opening_tag->location->start->column
          - closing_tag->value
          - closing_tag->location->start->line
          - closing_tag->location->start->column

      fields:
        - name: opening_tag
          type: token

        - name: closing_tag
          type: token

    - name: QuotesMismatchError
      message:
        template: "String opened with %s but closed with %s at (%zu:%zu)."
        arguments:
          - opening_quote->value
          - closing_quote->value
          - closing_quote->location->start->line
          - closing_quote->location->start->column

      fields:
        - name: opening_quote
          type: token

        - name: closing_quote
          type: token

    - name: VoidElementClosingTagError
      message:
        template: "`%s` is a void element and should not be used as a closing tag. Use `<%s>` or `<%s />` instead of `</%s>`."
        arguments:
          - tag_name->value
          - tag_name->value
          - tag_name->value
          - tag_name->value

      fields:
        - name: tag_name
          type: token

        - name: expected
          type: string

        - name: found
          type: string

    - name: UnclosedElementError
      message:
        template: "Tag `<%s>` opened at (%zu:%zu) was never closed before the end of document."
        arguments:
          - opening_tag->value
          - opening_tag->location->start->line
          - opening_tag->location->start->column

      fields:
        - name: opening_tag
          type: token

warnings:
  fields: []
  types: []

nodes:
  # fields:
  #   - name: type
  #     type: ast_node_type
  #
  #   - name: start
  #     type: position
  #
  #   - name: end
  #     type: position
  #
  #   - name: errors
  #     type: array
  #     kind: error
  #
  #   # - name: warnings
  #   #  type: array
  #   #  kind: warning
  #
  #   # - name: range
  #   #   type: range

  types:
    - name: DocumentNode
      fields:
        - name: children
          type: array

    - name: LiteralNode
      fields:
        - name: content
          type: string

    - name: HTMLOpenTagNode
      fields:
        - name: tag_opening
          type: token

        - name: tag_name
          type: token

        - name: attributes
          type: array
          kind: HTMLAttributeNode

        - name: tag_closing
          type: token

        - name: children
          type: array

        - name: is_void
          type: boolean

    - name: HTMLCloseTagNode
      fields:
        - name: tag_opening
          type: token

        - name: tag_name
          type: token

        - name: tag_closing
          type: token

    - name: HTMLSelfCloseTagNode
      fields:
        - name: tag_opening
          type: token

        - name: tag_name
          type: token

        - name: attributes
          type: array
          kind: HTMLAttributeNode

        - name: tag_closing
          type: token

        - name: is_void
          type: boolean

    - name: HTMLElementNode
      fields:
        - name: open_tag
          type: node
          kind: HTMLOpenTagNode

        - name: tag_name
          type: token

        - name: body
          type: array

        - name: close_tag
          type: node
          kind: HTMLCloseTagNode

        - name: is_void
          type: boolean

    - name: HTMLAttributeValueNode
      fields:
        - name: open_quote
          type: token

        - name: children
          type: array

        - name: close_quote
          type: token

        - name: quoted
          type: boolean

    - name: HTMLAttributeNameNode
      fields:
        - name: name
          type: token

    - name: HTMLAttributeNode
      fields:
        - name: name
          type: node
          kind: HTMLAttributeNameNode

        - name: equals
          type: token

        - name: value
          type: node
          kind: HTMLAttributeValueNode

    - name: HTMLTextNode
      fields:
        - name: content
          type: string

    - name: HTMLCommentNode
      fields:
        - name: comment_start
          type: token

        - name: children
          type: array

        - name: comment_end
          type: token

    - name: HTMLDoctypeNode
      fields:
        - name: tag_opening
          type: token

        - name: children
          type: array

        - name: tag_closing
          type: token

    - name: WhitespaceNode
      fields:
        - name: value
          type: token

    - name: ERBContentNode
      fields:
        - name: tag_opening
          type: token

        - name: content
          type: token

        - name: tag_closing
          type: token
