---
name: cache_if
source: "ActionView::Helpers::CacheHelper#cache_if"
gem: actionview
output: void
visibility: public
supported: false
supports_block: true
description: |-
  Cache fragments of a view if condition is true.
signature: "cache_if(condition, name = {}, options = {}, &block)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/CacheHelper.html#method-i-cache_if"
tag: null
arguments:
  - name: condition
    position: 1
    type: boolean
    optional: false
    description: "Condition to evaluate."
  - name: name
    position: 2
    type: [string, hash, object]
    optional: true
    default: "{}"
    description: "Cache key."
options: []
special_behaviors: []
