---
name: collection_radio_buttons
source: "ActionView::Helpers::FormOptionsHelper#collection_radio_buttons"
gem: actionview
output: html
visibility: public
supported: false
supports_block: true
description: |-
  Returns radio button tags for the collection of existing return values of `method` for `object`'s class. The value returned from calling `method` on the instance `object` will be selected. If calling `method` returns `nil`, no selection is made.
signature: "collection_radio_buttons(object, method, collection, value_method, text_method, options = {}, html_options = {}, &block)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_radio_buttons"
tag: null
arguments:
  - name: object
    position: 1
    type: [string, symbol]
    optional: false
    description: "The object name."
  - name: method
    position: 2
    type: [string, symbol]
    optional: false
    description: "The attribute of the object."
  - name: collection
    position: 3
    type: array
    optional: false
    description: "The collection of objects to build radio buttons from."
  - name: value_method
    position: 4
    type: [symbol, string]
    optional: false
    description: "Method to call on each member of `collection` to get the radio button value."
  - name: text_method
    position: 5
    type: [symbol, string]
    optional: false
    description: "Method to call on each member of `collection` to get the label text."
  - name: options
    position: 6
    type: hash
    optional: true
    default: "{}"
    description: "Options hash."
  - name: html_options
    position: 7
    type: hash
    optional: true
    default: "{}"
    description: "HTML attributes for each radio button tag."
options:
  - name: include_hidden
    type: boolean
    description: "If `false`, prevents the hidden field from being generated."
special_behaviors: []
