# frozen_string_literal: true

require "rake/testtask"
require "rake/extensiontask"

Rake::ExtensionTask.new("herb_linter") do |ext|
  ext.ext_dir = "ext/herb-linter"
  ext.lib_dir = "lib/herb/linter"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: [:compile, :test]
