---
name: "cookies"
source: "ActionView::Helpers::ControllerHelper#cookies"
gem: "actionview"
output: "object"
visibility: "internal"
supported: false
supports_block: false
signature: "cookies"
documentation_url: ""

description: |-
  Returns the cookies for the current request. Delegated to the controller. See `ActionDispatch::Cookies`.

tag: null
arguments: []
options: []
special_behaviors: []
