---
name: "headers"
source: "ActionView::Helpers::ControllerHelper#headers"
gem: "actionview"
output: "object"
visibility: "internal"
supported: false
supports_block: false
signature: "headers"
documentation_url: ""

description: |-
  Returns the response headers hash. Delegated to the controller.

tag: null
arguments: []
options: []
special_behaviors: []
