---
name: logger
source: "ActionView::Helpers::ControllerHelper#logger"
gem: actionview
output: text
visibility: internal
supported: false
supports_block: false
description: |-
  Returns the logger instance from the controller.
signature: "logger"
documentation_url: ""
tag: null
arguments: []
options: []
special_behaviors: []
aliases:
  - "logger?"
