---
name: response
source: "ActionView::Helpers::ControllerHelper#response"
gem: actionview
output: object
visibility: internal
supported: false
supports_block: false
description: |-
  Returns the current `ActionDispatch::Response` object. Delegated to the controller.
signature: "response"
documentation_url: ""
tag: null
arguments: []
options: []
special_behaviors: []
