---
name: hidden_field_tag
source: "ActionView::Helpers::FormTagHelper#hidden_field_tag"
gem: actionview
output: html
visibility: public
supported: false
supports_block: false
description: |-
  Creates a hidden form input field used to transmit data that would be lost due to HTTP's statelessness or data that should be hidden from the user.
signature: "hidden_field_tag(name, value = nil, options = {})"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-hidden_field_tag"
tag:
  name: input
  is_void: true
  preferred: false
  detect_style: call_name
arguments:
  - name: name
    position: 1
    type: string
    optional: false
    description: "Name attribute for the hidden input."
  - name: value
    position: 2
    type: string
    optional: true
    default: "nil"
    description: "Value of the hidden input."
  - name: options
    position: 3
    type: hash
    optional: true
    default: "{}"
    description: "HTML attributes hash."
options: []
special_behaviors: []
