---
name: strip_links
source: "ActionView::Helpers::SanitizeHelper#strip_links"
gem: actionview
output: text
visibility: public
supported: false
supports_block: false
description: |-
  Strips all link tags from text, leaving just the link text.
signature: "strip_links(html)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_links"
tag: null
arguments:
  - name: html
    position: 1
    type: string
    optional: false
    description: "HTML string to strip links from."
options: []
special_behaviors: []
