---
name: "form_with_generates_remote_forms"
source: "ActionView::Helpers::FormHelper#form_with_generates_remote_forms"
gem: "actionview"
output: "boolean"
visibility: "internal"
supported: false
supports_block: false
signature: "form_with_generates_remote_forms"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html"

description: |-
  Returns whether `form_with` generates `data-remote` forms by default.

tag: null
arguments: []
options: []
special_behaviors: []
