---
name: "multipart"
source: "ActionView::Helpers::FormHelper#multipart"
gem: "actionview"
output: "boolean"
visibility: "internal"
supported: false
supports_block: false
signature: "multipart"
documentation_url: ""

description: |-
  Returns whether the form builder has been set to use `multipart/form-data` encoding.

tag: null
arguments: []
options: []
block_arguments: []
special_behaviors: []
