---
comparisons:
  - operator: "=="
    negated: "!="

  - operator: "!="
    negated: "=="

  - operator: ">"
    mirrored: "<"
    negated: "<="
    ordered: true

  - operator: ">="
    mirrored: "<="
    negated: "<"
    ordered: true

  - operator: "<"
    mirrored: ">"
    negated: ">="
    ordered: true

  - operator: "<="
    mirrored: ">="
    negated: ">"
    ordered: true
