use std::collections::HashMap;
use std::sync::LazyLock;

use super::types::{ContentModel, ElementCategory, ElementDef, ElementScope};

fn element(
  tag_name: &'static str,
  categories: Vec<ElementCategory>,
  scope: ElementScope,
  content_model: ContentModel,
  required_attributes: Vec<&'static str>,
  supports_disabled: bool,
) -> ElementDef {
  ElementDef {
    tag_name,
    categories,
    scope,
    content_model,
    required_attributes,
    supports_disabled,
  }
}

use ElementCategory::*;
use ElementScope::*;

pub static HTML_ELEMENTS: LazyLock<HashMap<&'static str, ElementDef>> = LazyLock::new(|| {
  let entries: Vec<ElementDef> = vec![
    element("html", vec![], DocumentRoot, ContentModel::Flow, vec![], false),
    element("head", vec![Metadata], HtmlOnly, ContentModel::Flow, vec![], false),
    element("body", vec![Block], HtmlOnly, ContentModel::Flow, vec![], false),
    element("base", vec![Void, Metadata], HeadOnly, ContentModel::Empty, vec![], false),
    element("link", vec![Void, Metadata], HeadOnly, ContentModel::Empty, vec![], false),
    element("meta", vec![Void, Metadata], HeadOnly, ContentModel::Empty, vec![], false),
    element("style", vec![Metadata], HeadOnly, ContentModel::RawText, vec![], false),
    element("title", vec![Metadata], HeadOnly, ContentModel::RawText, vec![], false),
    element("script", vec![Inline, Metadata], HeadOrBody, ContentModel::RawText, vec![], false),
    element("noscript", vec![Block, Metadata], HeadOrBody, ContentModel::Flow, vec![], false),
    element("template", vec![Metadata], HeadOrBody, ContentModel::Flow, vec![], false),
    element("area", vec![Void, Inline], BodyOnly, ContentModel::Empty, vec![], false),
    element("br", vec![Void, Inline], BodyOnly, ContentModel::Empty, vec![], false),
    element("col", vec![Void], BodyOnly, ContentModel::Empty, vec![], false),
    element("embed", vec![Void, Inline, Embedded], BodyOnly, ContentModel::Empty, vec![], false),
    element("hr", vec![Void, Block], BodyOnly, ContentModel::Empty, vec![], false),
    element("img", vec![Void, Inline, Embedded], BodyOnly, ContentModel::Empty, vec!["alt"], false),
    element(
      "input",
      vec![Void, Inline, Interactive, FormAssociated],
      BodyOnly,
      ContentModel::Empty,
      vec![],
      true,
    ),
    element("param", vec![Void], BodyOnly, ContentModel::Empty, vec![], false),
    element("source", vec![Void], BodyOnly, ContentModel::Empty, vec![], false),
    element("track", vec![Void], BodyOnly, ContentModel::Empty, vec![], false),
    element("wbr", vec![Void, Inline], BodyOnly, ContentModel::Empty, vec![], false),
    element("article", vec![Block, Sectioning], BodyOnly, ContentModel::Flow, vec![], false),
    element("aside", vec![Block, Sectioning], BodyOnly, ContentModel::Flow, vec![], false),
    element("nav", vec![Block, Sectioning], BodyOnly, ContentModel::Flow, vec![], false),
    element("section", vec![Block, Sectioning], BodyOnly, ContentModel::Flow, vec![], false),
    element("h1", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("h2", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("h3", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("h4", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("h5", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("h6", vec![Block, Heading], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("address", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("blockquote", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("div", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("figure", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("figcaption", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("footer", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("header", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("main", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("p", vec![Block], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("pre", vec![Block], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("ol", vec![Block], BodyOnly, ContentModel::SpecificChildren(vec!["li"]), vec![], false),
    element("ul", vec![Block], BodyOnly, ContentModel::SpecificChildren(vec!["li"]), vec![], false),
    element("li", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("dl", vec![Block], BodyOnly, ContentModel::SpecificChildren(vec!["dt", "dd"]), vec![], false),
    element("dt", vec![Block], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("dd", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element(
      "table",
      vec![Block],
      BodyOnly,
      ContentModel::SpecificChildren(vec!["caption", "colgroup", "thead", "tbody", "tfoot", "tr"]),
      vec![],
      false,
    ),
    element("caption", vec![], BodyOnly, ContentModel::Flow, vec![], false),
    element("colgroup", vec![], BodyOnly, ContentModel::SpecificChildren(vec!["col"]), vec![], false),
    element("thead", vec![], BodyOnly, ContentModel::SpecificChildren(vec!["tr"]), vec![], false),
    element("tbody", vec![], BodyOnly, ContentModel::SpecificChildren(vec!["tr"]), vec![], false),
    element("tfoot", vec![Block], BodyOnly, ContentModel::SpecificChildren(vec!["tr"]), vec![], false),
    element("tr", vec![], BodyOnly, ContentModel::SpecificChildren(vec!["th", "td"]), vec![], false),
    element("th", vec![], BodyOnly, ContentModel::Flow, vec![], false),
    element("td", vec![], BodyOnly, ContentModel::Flow, vec![], false),
    element("form", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("fieldset", vec![Block, FormAssociated], BodyOnly, ContentModel::Flow, vec![], true),
    element("legend", vec![], BodyOnly, ContentModel::Phrasing, vec![], false),
    element(
      "label",
      vec![Inline, Interactive, FormAssociated],
      BodyOnly,
      ContentModel::Phrasing,
      vec![],
      false,
    ),
    element(
      "button",
      vec![Inline, Interactive, FormAssociated],
      BodyOnly,
      ContentModel::Phrasing,
      vec![],
      true,
    ),
    element(
      "select",
      vec![Inline, Interactive, FormAssociated],
      BodyOnly,
      ContentModel::SpecificChildren(vec!["option", "optgroup"]),
      vec![],
      true,
    ),
    element("option", vec![FormAssociated], BodyOnly, ContentModel::Phrasing, vec![], true),
    element(
      "optgroup",
      vec![FormAssociated],
      BodyOnly,
      ContentModel::SpecificChildren(vec!["option"]),
      vec![],
      true,
    ),
    element(
      "textarea",
      vec![Inline, Interactive, FormAssociated],
      BodyOnly,
      ContentModel::RawText,
      vec![],
      true,
    ),
    element("output", vec![Inline, FormAssociated], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("progress", vec![Inline, FormAssociated], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("meter", vec![Inline, FormAssociated], BodyOnly, ContentModel::Phrasing, vec![], false),
    element(
      "datalist",
      vec![FormAssociated],
      BodyOnly,
      ContentModel::SpecificChildren(vec!["option"]),
      vec![],
      false,
    ),
    element("a", vec![Inline, Interactive], BodyOnly, ContentModel::Transparent, vec!["href"], false),
    element("abbr", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("acronym", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("b", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("bdo", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("big", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("cite", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("code", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("dfn", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("em", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("i", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("kbd", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("mark", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("q", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("samp", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("small", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("span", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("strong", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("sub", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("sup", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("time", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("tt", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("var", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("audio", vec![Inline, Embedded], BodyOnly, ContentModel::Transparent, vec![], false),
    element("canvas", vec![Block, Inline, Embedded], BodyOnly, ContentModel::Transparent, vec![], false),
    element("iframe", vec![Inline, Embedded], BodyOnly, ContentModel::Empty, vec!["title"], false),
    element("map", vec![Inline], BodyOnly, ContentModel::Transparent, vec![], false),
    element("object", vec![Inline, Embedded], BodyOnly, ContentModel::Transparent, vec![], false),
    element(
      "picture",
      vec![Embedded],
      BodyOnly,
      ContentModel::SpecificChildren(vec!["source", "img"]),
      vec![],
      false,
    ),
    element("video", vec![Block, Inline, Embedded], BodyOnly, ContentModel::Transparent, vec![], false),
    element("details", vec![Block, Interactive], BodyOnly, ContentModel::Flow, vec![], false),
    element("summary", vec![Interactive], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("dialog", vec![Block], BodyOnly, ContentModel::Flow, vec![], false),
    element("del", vec![Inline], BodyOnly, ContentModel::Transparent, vec![], false),
    element("ins", vec![Inline], BodyOnly, ContentModel::Transparent, vec![], false),
    element("slot", vec![], BodyOnly, ContentModel::Transparent, vec![], false),
    element("data", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("ruby", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("rp", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("rt", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("s", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
    element("u", vec![Inline], BodyOnly, ContentModel::Phrasing, vec![], false),
  ];

  entries.into_iter().map(|entry| (entry.tag_name, entry)).collect()
});
