---
name: font_path
source: "ActionView::Helpers::AssetUrlHelper#font_path"
gem: actionview
output: url
visibility: public
supported: false
supports_block: false
description: |-
  Computes the path to a font asset.
signature: "font_path(source, options = {})"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html#method-i-font_path"
tag: null
arguments:
  - name: source
    position: 1
    type: string
    optional: false
    description: "Font file name or path."
options: []
special_behaviors: []
aliases:
  - path_to_font
