---
name: javascript_url
source: "ActionView::Helpers::AssetUrlHelper#javascript_url"
gem: actionview
output: url
visibility: public
supported: false
supports_block: false
description: |-
  Computes the full URL to a JavaScript asset.
signature: "javascript_url(source, options = {})"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html#method-i-javascript_url"
tag: null
arguments:
  - name: source
    position: 1
    type: string
    optional: false
    description: "JavaScript file name or path."
options: []
special_behaviors: []
aliases:
  - url_to_javascript
