---
name: "public_compute_asset_path"
source: "ActionView::Helpers::AssetUrlHelper#public_compute_asset_path"
gem: "actionview"
output: "boolean"
visibility: "internal"
supported: false
supports_block: false
signature: "public_compute_asset_path"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html"

description: |-
  Public alias for `compute_asset_path`. Computes the full asset path for a given source.

tag: null
arguments: []
options: []
block_arguments: []
special_behaviors: []
