---
name: stylesheet_url
source: "ActionView::Helpers::AssetUrlHelper#stylesheet_url"
gem: actionview
output: url
visibility: public
supported: false
supports_block: false
description: |-
  Computes the full URL to a stylesheet asset.
signature: "stylesheet_url(source, options = {})"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html#method-i-stylesheet_url"
tag: null
arguments:
  - name: source
    position: 1
    type: string
    optional: false
    description: "Stylesheet file name or path."
options: []
special_behaviors: []
aliases:
  - url_to_stylesheet
