import dedent from "dedent"
import { describe, test, expect, beforeEach, afterEach } from "vitest"
import { mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "fs"
import { join } from "path"
import { tmpdir } from "os"

import { Config } from "../src/config.js"

describe("Config todo file", () => {
  let testDir: string

  beforeEach(() => {
    testDir = join(tmpdir(), `herb-config-todo-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(testDir, { recursive: true })

    writeFileSync(join(testDir, ".herb.yml"), dedent`
      version: 0.11.0
      linter:
        enabled: true
    `)
  })

  afterEach(() => {
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true })
    }
  })

  function writeTodo(content: string) {
    writeFileSync(join(testDir, ".herb_todo.yml"), content)
  }

  test("disables a rule only for the files listed in .herb_todo.yml", async () => {
    writeTodo(dedent`
      html-img-require-alt:
        exclude:
          - app/views/legacy.html.erb
    `)

    const config = await Config.load(testDir, { silent: true })

    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/legacy.html.erb")).toBe(false)
    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/new.html.erb")).toBe(true)
    expect(config.isRuleEnabledForPath("html-tag-name-lowercase", "app/views/legacy.html.erb")).toBe(true)
  })

  test("keeps the rule's own exclude patterns from .herb.yml", async () => {
    writeFileSync(join(testDir, ".herb.yml"), dedent`
      version: 0.11.0
      linter:
        rules:
          html-img-require-alt:
            exclude:
              - app/views/mailers/**/*
    `)

    writeTodo(dedent`
      html-img-require-alt:
        exclude:
          - app/views/legacy.html.erb
    `)

    const config = await Config.load(testDir, { silent: true })

    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/mailers/welcome.html.erb")).toBe(false)
    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/legacy.html.erb")).toBe(false)
    expect(config.options.linter?.rules?.["html-img-require-alt"]?.exclude).toEqual(["app/views/mailers/**/*"])
  })

  test("does not touch linter.rules, so a rule's built-in excludes still apply", async () => {
    writeTodo(dedent`
      html-tag-name-lowercase:
        exclude:
          - app/views/legacy.html.erb
    `)

    const config = await Config.load(testDir, { silent: true })

    expect(config.options.linter?.rules?.["html-tag-name-lowercase"]).toBeUndefined()
    expect(config.todoExcludes).toEqual({ "html-tag-name-lowercase": ["app/views/legacy.html.erb"] })
  })

  test("skips the todo file when loaded with todo: false", async () => {
    writeTodo(dedent`
      html-img-require-alt:
        exclude:
          - app/views/legacy.html.erb
    `)

    const config = await Config.load(testDir, { silent: true, todo: false })

    expect(config.todoExcludes).toEqual({})
    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/legacy.html.erb")).toBe(true)
  })

  test("loads the todo file next to an explicit --config-file path", async () => {
    writeTodo(dedent`
      html-img-require-alt:
        exclude:
          - app/views/legacy.html.erb
    `)

    const config = await Config.load(join(testDir, ".herb.yml"), { silent: true })

    expect(config.isRuleEnabledForPath("html-img-require-alt", "app/views/legacy.html.erb")).toBe(false)
  })

  test("has no todo excludes when the file is missing", async () => {
    const config = await Config.load(testDir, { silent: true })

    expect(config.todoExcludes).toEqual({})
  })

  test("rejects a todo file with an unknown key", async () => {
    writeTodo(dedent`
      html-img-require-alt:
        enabled: false
    `)

    await expect(Config.load(testDir, { silent: true })).rejects.toThrow(/\.herb_todo\.yml/)
  })

  describe("Config.writeTodoFile", () => {
    test("writes the rules and files sorted, under a generated header", async () => {
      await Config.writeTodoFile(testDir, {
        "html-tag-name-lowercase": ["app/views/b.html.erb", "app/views/a.html.erb"],
        "html-img-require-alt": ["app/views/c.html.erb"],
      })

      const content = readFileSync(join(testDir, ".herb_todo.yml"), "utf-8")

      expect(content).toMatch(/^# This file was generated by `herb-lint --generate-todo`/)
      expect(content.indexOf("html-img-require-alt")).toBeLessThan(content.indexOf("html-tag-name-lowercase"))
      expect(content.indexOf("a.html.erb")).toBeLessThan(content.indexOf("b.html.erb"))

      const config = await Config.load(testDir, { silent: true })

      expect(config.todoExcludes).toEqual({
        "html-img-require-alt": ["app/views/c.html.erb"],
        "html-tag-name-lowercase": ["app/views/a.html.erb", "app/views/b.html.erb"],
      })
    })

    test("removes the todo file when there is nothing left to exclude", async () => {
      writeTodo(dedent`
        html-img-require-alt:
          exclude:
            - app/views/legacy.html.erb
      `)

      await Config.writeTodoFile(testDir, {})

      expect(existsSync(join(testDir, ".herb_todo.yml"))).toBe(false)
    })
  })
})
