---
name: "object"
source: "ActionView::Helpers::ActiveModelHelper#object"
gem: "actionview"
output: "text"
visibility: "internal"
supported: false
supports_block: false
signature: "object"
documentation_url: ""

description: |-
  Returns the model object associated with the form builder.

tag: null
arguments: []
options: []
special_behaviors: []
