---
name: capture
source: "ActionView::Helpers::CaptureHelper#capture"
gem: actionview
output: html
visibility: public
supported: false
supports_block: true
description: |-
  Extracts a part of a template as a string object. Useful for capturing markup for later use.
signature: "capture(*, **, &block)"
documentation_url: "https://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-capture"
tag: null
arguments: []
options: []
special_behaviors: []
