---
name: "with_output_buffer"
source: "ActionView::Helpers::CaptureHelper#with_output_buffer"
gem: "actionview"
output: "html"
visibility: "internal"
supported: false
supports_block: true
signature: "with_output_buffer(buf = nil, &block)"
documentation_url: ""

description: |-
  Swaps the output buffer for the duration of the block and returns the captured content as a string.

tag: null
arguments: []
options: []
block_arguments: []
special_behaviors: []
