name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubicloud-standard-2
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add LLVM apt Repo
        run: |-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-21 main"
          sudo apt update

      - name: Install APT dependencies
        run: xargs sudo apt-get install -y --no-install-recommends < Aptfile

      - name: Install valgrind
        run: |-
          sudo apt install -y libc6-dbg
          sudo snap install --classic valgrind

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: Render Templates
        run: bundle exec rake templates

      - name: Compile Herb
        run: bundle exec rake make

      - name: Compile Ruby extension
        run: bundle exec rake compile

      - name: Run Ruby Tests
        run: bundle exec rake test

      - name: Steep
        run: bundle exec steep check

      - name: RBS Inline
        run: bundle exec rake rbs_inline

      # - name: Sorbet
      #   run: bundle exec srb tc

      - name: Run C tests
        run: ./run_herb_tests

      - name: Run valgrind on examples/
        run: ./bin/valgrind_check_examples

      - name: clang-format version
        run: clang-format-21 --version

      - name: Lint
        run: bin/lint

      - name: clang-tidy version
        run: clang-tidy-21 --version

      - name: Tidy
        run: bin/tidy

      - name: RuboCop
        run: bundle exec rubocop
