name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install APT dependencies
        run: xargs sudo apt-get install -y < Aptfile

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: make bundle_install
        run: make bundle_install

      - name: make prism
        run: make prism

      - name: bundle show prism
        run: bundle show prism

      - name: make erbx_prism
        run: make erbx_prism

      - name: make
        run: make

      - name: run tests
        run: ./run_erbx_tests

      - name: clang-format version
        run: clang-format-19 --version

      - name: Lint
        run: bin/lint

      - name: clang-tidy version
        run: clang-tidy-19 --version

      - name: Tidy
        run: bin/tidy
