name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubicloud-standard-2
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        id: system-deps
        background: true
        run: |-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-21 main"
          sudo apt update
          xargs sudo apt-get install -y --no-install-recommends < Aptfile
          sudo apt install -y libc6-dbg
          sudo snap install --classic valgrind

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: Render Templates
        run: bundle exec rake templates

      - name: RuboCop
        id: rubocop
        background: true
        run: bundle exec rubocop

      - name: Sorbet
        id: sorbet
        background: true
        run: bundle exec srb tc

      - name: RBS Validation, Steep and RBS Inline
        id: rbs
        background: true
        run: |-
          bundle exec rbs collection install --frozen
          bundle exec rbs -Isig validate
          bundle exec steep check
          bundle exec rake rbs_inline

      - name: Wait for system dependencies
        wait: system-deps

      - name: Lint
        id: lint
        background: true
        run: |-
          clang-format-21 --version
          bin/lint

      - name: Tidy
        id: tidy
        background: true
        run: |-
          clang-tidy-21 --version
          bin/tidy

      - name: Compile Herb
        run: bundle exec rake make

      - name: Compile Ruby extension
        run: bundle exec rake compile

      - name: Wait for all checks
        wait-all:

      - name: Run Ruby Tests
        run: bundle exec rake test:all

      - name: Run C tests
        run: ./run_herb_tests

      - name: Run valgrind on examples/
        run: ./bin/valgrind_check_examples
