name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: Render Templates
        run: bundle exec rake templates

      - name: Build Prism
        run: bundle exec make prism

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed --locked

      - name: Build benchmarks
        run: cargo codspeed build --measurement-mode simulation --package herb --package herb-printer
        working-directory: rust

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: cargo codspeed run --package herb --package herb-printer
          working-directory: rust
