name: C Tests

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install check

      - name: make
        run: make

      - name: make test
        run: make test

      - name: run tests
        run: ./run_erbx_tests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format-19

      - name: clang-format version
        run: clang-format-19 --version

      - name: Lint
        run: bin/lint

  tidy:
    name: Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: clang-tidy version
        run: clang-tidy --version

      - name: Tidy
        run: bin/tidy
